Initial pass at printable report
acteng/inspectorate_tools pull request #89
Opened 2024-09-26 10:51 UTC by Pete-Y-CS

I think the wording will consideration, and we will want to share the layout more intelligently between the report page and the printable report page, but this is is okay proof of concept to show Will & Jadene

2024-09-30 10:36 UTC, dabreegster requested changes

2024-09-30 10:36 UTC, dabreegster commented on src/routes/planning/report/printable/+page@.svelte
> +<div class="govuk-width-container">
Should there at least be some kind of label / title at the top? There's a lack of context here. How about something like "Planning Application Assessment Toolkit Report"
![image](https://github.com/user-attachments/assets/d744a8c1-7046-47a2-b340-f3829d57899a)

2024-09-30 10:36 UTC, dabreegster commented on src/routes/planning/report/printable/+page@.svelte
> +    <caption class="govuk-table__caption govuk-table__caption--m">
Looks like all of this is exactly the same as the other report page. If so, a component to share between the two would be nice. The purpose of the new page is then just to discard some of the nav elements by using only the root layout

2024-09-30 10:36 UTC, dabreegster commented on src/routes/planning/report/+page.svelte
> +  window.open(`${base}/planning/report/printable`, '_blank').focus();
I'd remove the `.focus()`. There's a TS error here, because open can fail. I think `?.focus()` would fix it. But I tried without focus at all, and there's browser-dependant behavior to autofocus or not. In Firefox by default, it's a new tab that autofocuses. I expect that's probably fine for most users.

2024-09-30 10:46 UTC, Pete-Y-CS commented on src/routes/planning/report/printable/+page@.svelte
> +    <caption class="govuk-table__caption govuk-table__caption--m">
I intended to do this, and just before opening your review remembered I didn't get around to it 🙈. On it

2024-09-30 10:51 UTC, dabreegster commented on src/routes/planning/report/printable/+page@.svelte
> +    <caption class="govuk-table__caption govuk-table__caption--m">
Probably worth fixing and merging the other PR first, since there's changes there

2024-09-30 11:23 UTC, Pete-Y-CS commented
Think this is sorted, seems to be working locally, formatted and checked

2024-10-01 10:17 UTC, Pete-Y-CS commented
Happy to merge this one?

2024-10-01 10:24 UTC, dabreegster approved these changes

2024-10-01 10:35 UTC, merged