Filter PMP by stage. #94
acteng/inspectorate_tools pull request #95
Opened 2024-11-28 15:22 UTC by dabreegster

2024-11-28 17:03 UTC, Pete-Y-CS requested changes

2024-11-28 17:03 UTC, Pete-Y-CS commented on src/routes/route_check/problems_map/+page.svelte
> +    if (!showDesign && stage == "Design") {
I think we also need a check if it is existing and ! resolved by design
`(!showDesign && (stage == "Design" || (stage == "Existing" && !resolvedByDesign))`

2024-12-02 09:17 UTC, Pete-Y-CS commented on src/routes/route_check/problems_map/+page.svelte
> +    if (!showDesign && stage == "Design") {
Sure but my thinking is: filtering by stage it exists at.
If something exists already, and is not resolved by design then it exists in both design stage and existing stage, no?

2024-12-02 09:32 UTC, dabreegster commented on src/routes/route_check/problems_map/+page.svelte
> +    if (!showDesign && stage == "Design") {
Ah, I see. I guess it depends what people expect the filters to mean -- "show me data I've marked as stage=design or stage=existing" vs "show me _unresolved_ issues at this stage". Could we get clarity from whoever originally asked for this? Or we could re-word these checkboxes.

2024-12-04 10:15 UTC, dabreegster commented
Checkbox updated as discussed, and fixed the bug where the user could get into an impossible state (design stage, resolved yes). PTAL @Pete-Y-CS

2024-12-04 10:21 UTC, Pete-Y-CS approved these changes
lgtm!

2024-12-04 10:23 UTC, merged